<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="9" ignored="9" total="21" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="FlipKartExecutionSuite" duration-ms="63572" started-at="2018-08-25T08:10:53Z" finished-at="2018-08-25T08:11:56Z">
    <groups>
    </groups>
    <test name="IE suite" duration-ms="29120" started-at="2018-08-25T08:10:53Z" finished-at="2018-08-25T08:11:22Z">
      <class name="scripts.web.Home">
        <test-method status="PASS" signature="beforeTestBaseClass()[pri:0, instance:scripts.web.Home@3cef309d]" name="beforeTestBaseClass" is-config="true" duration-ms="0" started-at="2018-08-25T08:11:08Z" finished-at="2018-08-25T08:11:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestBaseClass -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Home@3cef309d]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="5225" started-at="2018-08-25T08:11:08Z" finished-at="2018-08-25T08:11:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="FAIL" signature="goToMenu()[pri:0, instance:scripts.web.Home@3cef309d]" name="goToMenu" duration-ms="480" started-at="2018-08-25T08:11:13Z" description="Verify Menu Navigation" finished-at="2018-08-25T08:11:14Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at businessLogic.webpages.HomePage.goToMenu(HomePage.java:45)
at scripts.web.Home.goToMenu(Home.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToMenu -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Home@3cef309d]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="3867" started-at="2018-08-25T08:11:14Z" finished-at="2018-08-25T08:11:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="FAIL" signature="verifyHomePageMainMenus()[pri:0, instance:scripts.web.Home@3cef309d]" name="verifyHomePageMainMenus" duration-ms="87" started-at="2018-08-25T08:11:18Z" description="Verify Main Menu on HomePage" finished-at="2018-08-25T08:11:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [0]: ELECTRONICS != Electronics expected [ELECTRONICS] but found [Electronics]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [0]: ELECTRONICS != Electronics expected [ELECTRONICS] but found [Electronics]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:831)
at org.testng.Assert.assertEquals(Assert.java:796)
at scripts.web.Home.verifyHomePageMainMenus(Home.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageMainMenus -->
      </class> <!-- scripts.web.Home -->
      <class name="scripts.web.Login">
        <test-method status="PASS" signature="getdriver()[pri:0, instance:scripts.web.Login@50b494a6]" name="getdriver" is-config="true" duration-ms="47" started-at="2018-08-25T08:10:52Z" finished-at="2018-08-25T08:10:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getdriver -->
        <test-method status="PASS" signature="beforeTestSetUp(java.lang.String)[pri:0, instance:scripts.web.Login@50b494a6]" name="beforeTestSetUp" is-config="true" duration-ms="3706" started-at="2018-08-25T08:10:53Z" finished-at="2018-08-25T08:10:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[IE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestSetUp -->
        <test-method status="PASS" signature="beforeTestBaseClass()[pri:0, instance:scripts.web.Login@50b494a6]" name="beforeTestBaseClass" is-config="true" duration-ms="0" started-at="2018-08-25T08:10:56Z" finished-at="2018-08-25T08:10:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestBaseClass -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Login@50b494a6]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="5751" started-at="2018-08-25T08:10:57Z" finished-at="2018-08-25T08:11:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="PASS" signature="loginWithInvalidPassword(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:scripts.web.Login@50b494a6]" name="loginWithInvalidPassword" duration-ms="337" started-at="2018-08-25T08:11:03Z" description="Verify Login with Invalid password" data-provider="Authentication" finished-at="2018-08-25T08:11:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test.gal12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Please enter valid Email ID/Mobile number]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidPassword -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Login@50b494a6]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="3922" started-at="2018-08-25T08:11:03Z" finished-at="2018-08-25T08:11:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="FAIL" signature="loginWithInvalidPassword(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:scripts.web.Login@50b494a6]" name="loginWithInvalidPassword" duration-ms="734" started-at="2018-08-25T08:11:07Z" description="Verify Login with Invalid password" data-provider="Authentication" finished-at="2018-08-25T08:11:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[tesdsst@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[swap]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Your username or password is not correct]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at businessLogic.webpages.LoginPage.verifyInvalidErrorMessage(LoginPage.java:48)
at scripts.web.Login.loginWithInvalidPassword(Login.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidPassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:scripts.web.Login@50b494a6]" name="tearDown" is-config="true" duration-ms="3496" started-at="2018-08-25T08:11:18Z" finished-at="2018-08-25T08:11:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- scripts.web.Login -->
    </test> <!-- IE suite -->
    <test name="Chrome suite" duration-ms="56387" started-at="2018-08-25T08:10:53Z" finished-at="2018-08-25T08:11:49Z">
      <class name="scripts.web.Home">
        <test-method status="PASS" signature="beforeTestBaseClass()[pri:0, instance:scripts.web.Home@6c3708b3]" name="beforeTestBaseClass" is-config="true" duration-ms="0" started-at="2018-08-25T08:11:37Z" finished-at="2018-08-25T08:11:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestBaseClass -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Home@6c3708b3]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="4437" started-at="2018-08-25T08:11:37Z" finished-at="2018-08-25T08:11:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="FAIL" signature="goToMenu()[pri:0, instance:scripts.web.Home@6c3708b3]" name="goToMenu" duration-ms="1566" started-at="2018-08-25T08:11:41Z" description="Verify Menu Navigation" finished-at="2018-08-25T08:11:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at businessLogic.webpages.HomePage.goToMenu(HomePage.java:45)
at scripts.web.Home.goToMenu(Home.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToMenu -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Home@6c3708b3]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="3684" started-at="2018-08-25T08:11:43Z" finished-at="2018-08-25T08:11:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="FAIL" signature="verifyHomePageMainMenus()[pri:0, instance:scripts.web.Home@6c3708b3]" name="verifyHomePageMainMenus" duration-ms="483" started-at="2018-08-25T08:11:47Z" description="Verify Main Menu on HomePage" finished-at="2018-08-25T08:11:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [0]: ELECTRONICS != Electronics expected [ELECTRONICS] but found [Electronics]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [0]: ELECTRONICS != Electronics expected [ELECTRONICS] but found [Electronics]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:831)
at org.testng.Assert.assertEquals(Assert.java:796)
at scripts.web.Home.verifyHomePageMainMenus(Home.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageMainMenus -->
      </class> <!-- scripts.web.Home -->
      <class name="scripts.web.Login">
        <test-method status="PASS" signature="beforeTestSetUp(java.lang.String)[pri:0, instance:scripts.web.Login@520a3426]" name="beforeTestSetUp" is-config="true" duration-ms="5437" started-at="2018-08-25T08:10:53Z" finished-at="2018-08-25T08:10:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestSetUp -->
        <test-method status="PASS" signature="beforeTestBaseClass()[pri:0, instance:scripts.web.Login@520a3426]" name="beforeTestBaseClass" is-config="true" duration-ms="0" started-at="2018-08-25T08:10:58Z" finished-at="2018-08-25T08:10:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestBaseClass -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Login@520a3426]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="28597" started-at="2018-08-25T08:10:58Z" finished-at="2018-08-25T08:11:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="PASS" signature="loginWithInvalidPassword(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:scripts.web.Login@520a3426]" name="loginWithInvalidPassword" duration-ms="1304" started-at="2018-08-25T08:11:27Z" description="Verify Login with Invalid password" data-provider="Authentication" finished-at="2018-08-25T08:11:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test.gal12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Please enter valid Email ID/Mobile number]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidPassword -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Login@520a3426]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="4426" started-at="2018-08-25T08:11:28Z" finished-at="2018-08-25T08:11:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="FAIL" signature="loginWithInvalidPassword(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:scripts.web.Login@520a3426]" name="loginWithInvalidPassword" duration-ms="3276" started-at="2018-08-25T08:11:33Z" description="Verify Login with Invalid password" data-provider="Authentication" finished-at="2018-08-25T08:11:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[tesdsst@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[swap]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Your username or password is not correct]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at businessLogic.webpages.LoginPage.verifyInvalidErrorMessage(LoginPage.java:48)
at scripts.web.Login.loginWithInvalidPassword(Login.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidPassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:scripts.web.Login@520a3426]" name="tearDown" is-config="true" duration-ms="1177" started-at="2018-08-25T08:11:48Z" finished-at="2018-08-25T08:11:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- scripts.web.Login -->
    </test> <!-- Chrome suite -->
    <test name="Firefox suite" duration-ms="63572" started-at="2018-08-25T08:10:53Z" finished-at="2018-08-25T08:11:56Z">
      <class name="scripts.web.Home">
        <test-method status="PASS" signature="beforeTestBaseClass()[pri:0, instance:scripts.web.Home@1f36e637]" name="beforeTestBaseClass" is-config="true" duration-ms="1" started-at="2018-08-25T08:11:40Z" finished-at="2018-08-25T08:11:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestBaseClass -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Home@1f36e637]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="5288" started-at="2018-08-25T08:11:40Z" finished-at="2018-08-25T08:11:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="FAIL" signature="goToMenu()[pri:0, instance:scripts.web.Home@1f36e637]" name="goToMenu" duration-ms="1276" started-at="2018-08-25T08:11:45Z" description="Verify Menu Navigation" finished-at="2018-08-25T08:11:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at businessLogic.webpages.HomePage.goToMenu(HomePage.java:45)
at scripts.web.Home.goToMenu(Home.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToMenu -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Home@1f36e637]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="4614" started-at="2018-08-25T08:11:46Z" finished-at="2018-08-25T08:11:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="FAIL" signature="verifyHomePageMainMenus()[pri:0, instance:scripts.web.Home@1f36e637]" name="verifyHomePageMainMenus" duration-ms="1153" started-at="2018-08-25T08:11:51Z" description="Verify Main Menu on HomePage" finished-at="2018-08-25T08:11:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [0]: ELECTRONICS != Electronics expected [ELECTRONICS] but found [Electronics]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [0]: ELECTRONICS != Electronics expected [ELECTRONICS] but found [Electronics]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:831)
at org.testng.Assert.assertEquals(Assert.java:796)
at scripts.web.Home.verifyHomePageMainMenus(Home.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageMainMenus -->
      </class> <!-- scripts.web.Home -->
      <class name="scripts.web.Login">
        <test-method status="PASS" signature="beforeTestSetUp(java.lang.String)[pri:0, instance:scripts.web.Login@2758fe70]" name="beforeTestSetUp" is-config="true" duration-ms="21795" started-at="2018-08-25T08:10:53Z" finished-at="2018-08-25T08:11:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestSetUp -->
        <test-method status="PASS" signature="beforeTestBaseClass()[pri:0, instance:scripts.web.Login@2758fe70]" name="beforeTestBaseClass" is-config="true" duration-ms="0" started-at="2018-08-25T08:11:14Z" finished-at="2018-08-25T08:11:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestBaseClass -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Login@2758fe70]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="15014" started-at="2018-08-25T08:11:15Z" finished-at="2018-08-25T08:11:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="PASS" signature="loginWithInvalidPassword(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:scripts.web.Login@2758fe70]" name="loginWithInvalidPassword" duration-ms="1002" started-at="2018-08-25T08:11:30Z" description="Verify Login with Invalid password" data-provider="Authentication" finished-at="2018-08-25T08:11:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test.gal12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Please enter valid Email ID/Mobile number]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidPassword -->
        <test-method status="PASS" signature="setUpBeforeBaseMethod()[pri:0, instance:scripts.web.Login@2758fe70]" name="setUpBeforeBaseMethod" is-config="true" duration-ms="6410" started-at="2018-08-25T08:11:31Z" finished-at="2018-08-25T08:11:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeBaseMethod -->
        <test-method status="FAIL" signature="loginWithInvalidPassword(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:scripts.web.Login@2758fe70]" name="loginWithInvalidPassword" duration-ms="1869" started-at="2018-08-25T08:11:37Z" description="Verify Login with Invalid password" data-provider="Authentication" finished-at="2018-08-25T08:11:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[tesdsst@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[swap]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Your username or password is not correct]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at businessLogic.webpages.LoginPage.verifyInvalidErrorMessage(LoginPage.java:48)
at scripts.web.Login.loginWithInvalidPassword(Login.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidPassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:scripts.web.Login@2758fe70]" name="tearDown" is-config="true" duration-ms="3711" started-at="2018-08-25T08:11:52Z" finished-at="2018-08-25T08:11:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- scripts.web.Login -->
    </test> <!-- Firefox suite -->
  </suite> <!-- FlipKartExecutionSuite -->
</testng-results>
